const menuToggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');
let menuReturnFocus=null;
const menuFocusable=()=>[menuToggle,...nav.querySelectorAll('a,button')].filter(element=>element&&!element.hasAttribute('disabled'));
const closeMenu=({restoreFocus=true}={})=>{nav.classList.remove('is-open');document.body.classList.remove('menu-open');if(window.matchMedia('(max-width:1100px)').matches){nav.setAttribute('aria-hidden','true')}else{nav.removeAttribute('aria-hidden')}menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Abrir menu');if(restoreFocus)menuReturnFocus?.focus()};
const openMenu=()=>{menuReturnFocus=document.activeElement;nav.classList.add('is-open');document.body.classList.add('menu-open');nav.setAttribute('aria-hidden','false');menuToggle.setAttribute('aria-expanded','true');menuToggle.setAttribute('aria-label','Fechar menu');menuFocusable()[1]?.focus()};
if(menuToggle&&nav){menuToggle.addEventListener('click',()=>nav.classList.contains('is-open')?closeMenu():openMenu());nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>closeMenu({restoreFocus:false})));document.addEventListener('keydown',event=>{if(!nav.classList.contains('is-open'))return;if(event.key==='Escape'){event.preventDefault();closeMenu();return}if(event.key!=='Tab')return;const elements=menuFocusable();if(!elements.length)return;const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}})}
const desktopNavigation=window.matchMedia('(min-width:1101px)');
const syncNavigationAccessibility=event=>{if(event.matches){nav?.removeAttribute('aria-hidden')}else if(!nav?.classList.contains('is-open')){nav?.setAttribute('aria-hidden','true')}};
syncNavigationAccessibility(desktopNavigation);
desktopNavigation.addEventListener?.('change',syncNavigationAccessibility);


const initAmbientes=()=>{
  const ambientesSection=document.querySelector('#ambientes');
  if(!ambientesSection||ambientesSection.classList.contains('is-enhanced'))return;
  // Remove o conteúdo legado antes de montar a experiência atual, evitando
  // que a versão antiga apareça durante a inicialização.
  ambientesSection.replaceChildren();
  const ambientes=[
    {numero:'01',id:'sala-copa',titulo:'Sala & copa',area:'17,37 m²',imagens:['imagens/copa-sala.webp','imagens/sala-cozinha-apartamento.webp'],angleLabels:['Outro ângulo','Vista principal']},
    {numero:'02',id:'cozinha',titulo:'Cozinha',imagens:['imagens/sala-cozinha-horizontal.webp','imagens/sala-cozinha-apartamento.webp']},
    {numero:'03',id:'quarto',titulo:'Quarto',imagens:['imagens/quarto-1.webp']},
    {numero:'04',id:'suite',titulo:'Suíte',imagens:['imagens/suite-horizontal.webp']},
    {numero:'05',id:'banheiro',titulo:'Banheiro',imagens:['imagens/banheiro-horizontal.webp']},
    {numero:'06',id:'sacada',titulo:'Sacada',imagens:['imagens/Sacada.webp']},
    {numero:'07',id:'garagem',titulo:'Garagem',imagens:['imagens/garagem-horizontal.webp']},
    {numero:'08',id:'escadas',titulo:'Escadas',imagens:['imagens/escada-horizontal.webp']},
    {numero:'09',id:'fachada',titulo:'Fachada',imagens:['imagens/faixada-horizontal.webp','imagens/bg-hero.webp']}
  ];
  const responsiveSource=src=>{const match=src.match(/^imagens\/(.+)\.webp$/);if(!match)return'';const width=match[1]==='Planta-1'?2400:1672;return`imagens/${match[1]}-768.webp 768w, imagens/${match[1]}-1200.webp 1200w, ${src} ${width}w`};
  ambientesSection.innerHTML=`<div class="room-tour-media"><img id="ambientes-image" src="${ambientes[0].imagens[0]}" srcset="${responsiveSource(ambientes[0].imagens[0])}" sizes="100vw" alt="Sala e cozinha integradas do Residencial Lourival Sgarioni"><div class="room-tour-overlay"></div></div><div class="room-tour-inner"><header class="ambientes-header"><p class="ambientes-kicker">Tour pelos cômodos</p><h2><span id="ambientes-title">Sala &amp; copa</span><small id="ambientes-area">17,37 m²</small></h2></header><aside class="ambientes-sidebar" aria-label="Ambientes do imóvel"><p class="ambientes-sidebar-label">Ambientes</p><nav id="ambientes-list"></nav></aside><div class="ambientes-mode" role="group" aria-label="Modo de visualização"><button class="is-active" type="button" data-mode="fotos"><svg aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"></rect><circle cx="8.5" cy="10" r="1.5"></circle><path d="m21 15-5-5L5 19"></path></svg>Fotos</button><button type="button" data-mode="planta" aria-label="Visualizar planta"><svg aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6.5 9 3l6 3.5L21 3v14.5L15 21l-6-3.5L3 21Z"></path><path d="M9 3v14.5M15 6.5V21"></path></svg>Planta</button></div><div class="ambientes-plan-controls" aria-label="Zoom da planta"><button type="button" data-plan-zoom="out" aria-label="Diminuir zoom da planta">−</button><output id="ambientes-plan-zoom-value">100%</output><button type="button" data-plan-zoom="in" aria-label="Aumentar zoom da planta">+</button></div><div class="ambientes-plan-pan" aria-hidden="true"></div><div class="ambientes-angles" id="ambientes-angles" aria-label="Ângulos da fotografia"></div><div class="ambientes-controls"><button type="button" id="ambientes-prev" aria-label="Ambiente anterior">←</button><button type="button" id="ambientes-next" aria-label="Próximo ambiente">→</button></div></div><div class="ambientes-mobile-list" id="ambientes-mobile-list" aria-label="Escolha um ambiente"></div>`;
  ambientesSection.classList.add('is-enhanced');
  ambientesSection.querySelector('#ambientes-prev').innerHTML='<svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"></path></svg>';
  ambientesSection.querySelector('#ambientes-next').innerHTML='<svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"></path></svg>';
  const mobileListContainer=ambientesSection.querySelector('#ambientes-mobile-list');mobileListContainer.after(ambientesSection.querySelector('.ambientes-mode'));
  const image=ambientesSection.querySelector('#ambientes-image'),title=ambientesSection.querySelector('#ambientes-title'),area=ambientesSection.querySelector('#ambientes-area'),list=ambientesSection.querySelector('#ambientes-list'),mobileList=ambientesSection.querySelector('#ambientes-mobile-list'),angles=ambientesSection.querySelector('#ambientes-angles'),planZoomValue=ambientesSection.querySelector('#ambientes-plan-zoom-value');
  const planPanToggle=document.createElement('button');planPanToggle.type='button';planPanToggle.className='ambientes-plan-toggle';planPanToggle.setAttribute('aria-label','Ativar movimento da planta');planPanToggle.setAttribute('aria-pressed','false');planPanToggle.innerHTML='<svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20"></path><path d="m15 19-3 3-3-3"></path><path d="m19 9 3 3-3 3"></path><path d="M2 12h20"></path><path d="m5 9-3 3 3 3"></path><path d="m9 5 3-3 3 3"></path></svg>';ambientesSection.querySelector('.ambientes-plan-controls').after(planPanToggle);
  let activeRoom=0,activeAngle=0,mode='fotos',planZoom=1,planOffsetX=0,planOffsetY=0,isPanActive=false,isDragging=false,dragStartX=0,dragStartY=0,dragOriginX=0,dragOriginY=0;
  const applyPlanTransform=()=>{image.style.transform=`translate(${planOffsetX}px, ${planOffsetY}px) scale(${planZoom})`;planZoomValue.textContent=`${Math.round(planZoom*100)}%`};
  const syncMediaAspect=()=>{if(mode==='planta'){ambientesSection.classList.remove('is-portrait');return}ambientesSection.classList.toggle('is-portrait',image.naturalHeight>image.naturalWidth)};
  let nextImagePrefetched=false;
  const prefetchNextImage=()=>{if(nextImagePrefetched||!ambientes[0].imagens[1])return;nextImagePrefetched=true;const preload=()=>{const nextImage=new Image();nextImage.srcset=responsiveSource(ambientes[0].imagens[1]);nextImage.sizes='100vw';nextImage.src=ambientes[0].imagens[1]};if('requestIdleCallback'in window)window.requestIdleCallback(preload,{timeout:1800});else window.setTimeout(preload,650)};
  image.width=1672;image.height=941;image.loading='lazy';image.decoding='async';image.addEventListener('load',()=>{syncMediaAspect();prefetchNextImage()});image.draggable=false;image.style.touchAction='pan-y';
  const altText=room=>`${room.titulo} do Residencial Lourival Sgarioni`;
  const angleLabel=(room,index)=>room.angleLabels?.[index]||(index===0?'Vista principal':'Outro ângulo');
  const renderRoom=(index,angle=0)=>{activeRoom=(index+ambientes.length)%ambientes.length;activeAngle=angle;const room=ambientes[activeRoom];title.textContent=mode==='planta'?'Planta':room.titulo;area.textContent=room.area||'';area.hidden=mode==='planta'||!room.area;image.classList.add('is-changing');setTimeout(()=>{const source=mode==='planta'?'imagens/Planta-1.webp':room.imagens[activeAngle];image.src=source;image.srcset=responsiveSource(source);image.sizes='100vw';image.alt=mode==='planta'?'Planta do imóvel Residencial Lourival Sgarioni':altText(room);image.classList.remove('is-changing');syncMediaAspect()},180);list.querySelectorAll('button').forEach((button,i)=>{button.classList.toggle('is-active',i===activeRoom);button.disabled=mode==='planta'});mobileList.querySelectorAll('button').forEach((button,i)=>{button.classList.toggle('is-active',i===activeRoom);button.disabled=mode==='planta'});angles.innerHTML=mode==='fotos'&&room.imagens.length>1?room.imagens.map((src,i)=>`<button type="button" class="${i===activeAngle?'is-active':''}" data-angle="${i}" aria-label="${angleLabel(room,i)}"><span>${String(i+1).padStart(2,'0')}</span><small>${angleLabel(room,i)}</small></button>`).join(''):'';angles.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>renderRoom(activeRoom,Number(button.dataset.angle))));};
  const roomIcon= id=>{const paths={
    'sala-copa':'<path d="M5 3h14l-1 9a6 6 0 0 1-12 0Z"></path><path d="M12 18v3M8 21h8"></path>',
    cozinha:'<path d="M5 11h14v9H5z"></path><path d="M5 11a3.5 3.5 0 0 1 2-6.4A4.5 4.5 0 0 1 12 3a4.5 4.5 0 0 1 5 1.6 3.5 3.5 0 0 1 2 6.4"></path><path d="M8 15h.01M12 15h.01M16 15h.01"></path>',
    quarto:'<path d="M2 20v-8a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v8"></path><path d="M4 14h16"></path><path d="M6 10V6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v4"></path>',
    suite:'<path d="M2 20v-8a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v8"></path><path d="M4 14h16"></path><path d="M6 10V6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v4"></path>',
    banheiro:'<path d="M3 12h18"></path><path d="M5 12v4a4 4 0 0 0 4 4h6a4 4 0 0 0 4-4v-4"></path><path d="M5 12V5a2 2 0 0 1 4 0v2"></path>',
    sacada:'<path d="M17.7 7.7a2.5 2.5 0 1 0-3.5-3.5"></path><path d="M3 12h15a3 3 0 1 1-3 3"></path><path d="M3 6h8M3 18h5"></path>',
    garagem:'<path d="M3 17h18l-2-8H5z"></path><circle cx="7" cy="17" r="1.5"></circle><circle cx="17" cy="17" r="1.5"></circle>',
    escadas:'<path d="M4 20h16M5 16h4v4M9 12h4v8M13 8h4v12"></path>',
    fachada:'<path d="M3 21h18M5 21V7l7-4 7 4v14M9 21v-5h6v5M8 10h.01M12 10h.01M16 10h.01"></path>'
  };return `<svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${paths[id]||paths.fachada}</svg>`};
  const roomButton=(room,index,compact=false)=>{const button=document.createElement('button');button.type='button';button.className=index===0?'is-active':'';const thumbnail=room.imagens[0].replace(/\.webp$/,'-240.webp');button.innerHTML=compact?`<span>${room.titulo}</span>`:`<img src="${thumbnail}" alt="" width="240" height="135" loading="lazy" fetchpriority="low" decoding="async"><span><small class="room-icon">${roomIcon(room.id)}</small>${room.titulo}</span>`;button.addEventListener('click',()=>renderRoom(index));return button;};
  ambientes.forEach((room,index)=>list.appendChild(roomButton(room,index)));ambientes.forEach((room,index)=>mobileList.appendChild(roomButton(room,index,true)));
  ambientesSection.querySelector('#ambientes-prev').addEventListener('click',()=>renderRoom(activeRoom-1));ambientesSection.querySelector('#ambientes-next').addEventListener('click',()=>renderRoom(activeRoom+1));
  ambientesSection.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.mode;image.style.touchAction='pan-y';isPanActive=false;planPanToggle.classList.remove('is-active');planPanToggle.setAttribute('aria-pressed','false');planPanToggle.setAttribute('aria-label','Ativar movimento da planta');ambientesSection.classList.remove('is-pan-active');ambientesSection.classList.toggle('is-plan',mode==='planta');ambientesSection.querySelectorAll('[data-mode]').forEach(item=>item.classList.toggle('is-active',item===button));planZoom=1;planOffsetX=0;planOffsetY=0;applyPlanTransform();renderRoom(activeRoom,activeAngle)}));
  ambientesSection.querySelectorAll('[data-plan-zoom]').forEach(button=>button.addEventListener('click',()=>{const maxZoom=window.matchMedia('(max-width: 820px)').matches?4.5:2.4;planZoom=Math.min(maxZoom,Math.max(1,planZoom+(button.dataset.planZoom==='in'?.2:-.2)));applyPlanTransform()}));
  const togglePanMode=event=>{event.preventDefault();event.stopPropagation();isPanActive=!isPanActive;image.style.touchAction=isPanActive?'none':'pan-y';planPanToggle.classList.toggle('is-active',isPanActive);planPanToggle.setAttribute('aria-pressed',String(isPanActive));planPanToggle.setAttribute('aria-label',isPanActive?'Desativar movimento da planta':'Ativar movimento da planta');ambientesSection.classList.toggle('is-pan-active',isPanActive)};planPanToggle.style.pointerEvents='auto';planPanToggle.addEventListener('pointerup',togglePanMode);planPanToggle.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){togglePanMode(event)}});
  const panSurface=ambientesSection.querySelector('.room-tour-media');panSurface.addEventListener('pointerdown',event=>{if(mode!=='planta'||!isPanActive)return;isDragging=true;dragStartX=event.clientX;dragStartY=event.clientY;dragOriginX=planOffsetX;dragOriginY=planOffsetY;panSurface.setPointerCapture(event.pointerId)});panSurface.addEventListener('pointermove',event=>{if(!isDragging)return;planOffsetX=dragOriginX+event.clientX-dragStartX;planOffsetY=dragOriginY+event.clientY-dragStartY;applyPlanTransform()});panSurface.addEventListener('pointerup',event=>{isDragging=false;panSurface.releasePointerCapture?.(event.pointerId)});panSurface.addEventListener('pointercancel',()=>{isDragging=false});
  renderRoom(0);
  document.dispatchEvent(new Event('roomtour:ready'));
};

const ambientesSection=document.querySelector('#ambientes');
if(ambientesSection){
  let ambientesStarted=false,ambientesObserver;
  const loadAmbientes=()=>{if(ambientesStarted)return;ambientesStarted=true;ambientesObserver?.disconnect();initAmbientes()};
  if(location.hash==='#ambientes')loadAmbientes();
  else if('IntersectionObserver'in window){ambientesObserver=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting))loadAmbientes()},{rootMargin:'500px 0px',threshold:0});ambientesObserver.observe(ambientesSection)}
  else window.addEventListener('load',loadAmbientes,{once:true});
  document.querySelectorAll('a[href="#ambientes"]').forEach(link=>link.addEventListener('click',loadAmbientes,{once:true,capture:true}));
}

import('./post-tour.js');
